# Generated by Django 5.0.7 on 2024-11-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_morningclasses'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveningClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='morningclasses',
            name='phone_no',
            field=models.IntegerField(max_length=100),
        ),
    ]
