# Generated by Django 5.0.7 on 2024-12-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_halfpackage_monthlypackage_yearlypackage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_no', models.IntegerField()),
                ('password', models.IntegerField()),
                ('confirm_password', models.IntegerField()),
            ],
        ),
    ]
